# IPython log file

runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', args='> output.txt', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/lexotree.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/lexotree.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
if []:
    print("hi")
    
[] == False
#[Out]# False
[] == True
#[Out]# False
[] is False
#[Out]# False
[] is True
#[Out]# False
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/lexotree.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/lexotree.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/lexotree.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/lexotree.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/lexotree.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
"1" == 1
#[Out]# False
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/delete1.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
runfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
debugfile('C:/Users/Admin/Google Drive/Computer Science/Dissertation/data/trees.py', wdir='C:/Users/Admin/Google Drive/Computer Science/Dissertation/data')
